dataset: meta-domain-net
train_set_args: 
  root: /srv/home/zxu444/datasets/domainNet/sketch_split
  split: meta-train
  size: 224           
  transform: dinov2
  n_batch: 200
  n_episode: 1
  n_way: 15
  n_shot: 1
  n_query: 9
  deterministic: True  # whether set images in dataset to be deterministic in each epoch
val_set_args:
  root: /srv/home/zxu444/datasets/domainNet/sketch_split
  split: meta-val
  size: 224           
  transform: make_classification_eval_transform
  n_batch: 200
  n_episode: 1
  n_way: 15
  n_shot: 1
  n_query: 10
  deterministic: True  # whether set images in dataset to be deterministic in each epoch


encoder: torchvision_RN50
LP: False

path: ./save/torchvision/domain-net/stdFT/meta-domain-net_torchvision_RN50_lp_logistic_15y1s_150m_200M
ckpt: lp_epoch-10.pth
LP_FT: True


classifier: fs-centroid
classifier_args:
  temp: 10.
  learn_temp: True

lp_optimizer: sgd
lp_optimizer_args:
  lr: 1.
  schedule: step
  decay_rate: 0.1
  decay_epochs:
    - 60
    - 80
  momentum: 0.9
  weight_decay: 0
lp_n_epochs: 30

optimizer: sgd
optimizer_args:
  lr: 1.e-7 # 0.001
  momentum: 0.9
  weight_decay: 5.e-6
n_epochs: 10

save_path: ./save/torchvision/domain-net/stdFT

save_epoch: 10
V: 1


